//パラメーター用のタグ
#define PARAM_DEPTH_TAG 11
#define PARAM_SPEED_TAG 12
#define PARAM_TYPE_TAG 13
#define PARAM_OSC1_OCTAVE_TAG 101
#define PARAM_OSC1_DETUNE_TAG 102
#define PARAM_OSC1_GAIN_TAG 103
#define PARAM_VOLUME_TAG 1001 

// detuneの分割数
#define DETUNE_NUM 8
